name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -Dspring.profiles.active=gcp

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Create app directory on server
        run: ssh -o StrictHostKeyChecking=no beamt348@${{ secrets.GCP_HOST }} 'mkdir -p /home/beamt348/app'

      - name: Transfer JAR to server
        run: scp -o StrictHostKeyChecking=no build/libs/teambeam-0.0.1-SNAPSHOT.jar beamt348@${{ secrets.GCP_HOST }}:/home/beamt348/app/teambeam-0.0.1-SNAPSHOT.jar

      - name: Deploy on GCP instance
        run: |
          ssh -o StrictHostKeyChecking=no beamt348@${{ secrets.GCP_HOST }} << 'EOF'
            echo "Stopping existing application using Actuator..."
            if curl -s -X POST http://localhost:8080/actuator/shutdown; then
              echo "Spring Boot application shutdown successfully."
              sleep 10  # 애플리케이션 종료 대기 시간
            else
              echo "Failed to shutdown Spring Boot application or it was not running. Attempting to kill the process..."
              pkill -f 'java -jar' || true
              sleep 10  # 애플리케이션 종료 대기 시간
            fi
          
            echo "Checking if port 8080 is free..."
            while sudo lsof -t -i tcp:8080; do
              sudo lsof -t -i tcp:8080 | xargs sudo kill -9 || true
              sleep 1
            done
          
            echo "Starting new application instance..."
            nohup java -jar /home/beamt348/app/teambeam-0.0.1-SNAPSHOT.jar --spring.profiles.active=gcp > /home/beamt348/app/app.log 2>&1 &
          EOF

